# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addclient.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addclient(object):
    def setupUi(self, addclient):
        addclient.setObjectName("addclient")
        addclient.resize(800, 300)
        addclient.setMinimumSize(QtCore.QSize(800, 300))
        addclient.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(addclient)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name = QtWidgets.QLabel(addclient)
        self.name.setMinimumSize(QtCore.QSize(38, 0))
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)
        self.line_name = QtWidgets.QLineEdit(addclient)
        self.line_name.setObjectName("line_name")
        self.horizontalLayout_2.addWidget(self.line_name)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.client_id = QtWidgets.QLabel(addclient)
        self.client_id.setMinimumSize(QtCore.QSize(43, 0))
        self.client_id.setMaximumSize(QtCore.QSize(43, 16777215))
        self.client_id.setWordWrap(True)
        self.client_id.setObjectName("client_id")
        self.horizontalLayout_3.addWidget(self.client_id)
        self.line_referral = QtWidgets.QLineEdit(addclient)
        self.line_referral.setMaximumSize(QtCore.QSize(336, 16777215))
        self.line_referral.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.line_referral.setReadOnly(True)
        self.line_referral.setObjectName("line_referral")
        self.horizontalLayout_3.addWidget(self.line_referral)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.deposit = QtWidgets.QLabel(addclient)
        self.deposit.setMinimumSize(QtCore.QSize(43, 0))
        self.deposit.setWordWrap(True)
        self.deposit.setObjectName("deposit")
        self.horizontalLayout_5.addWidget(self.deposit)
        self.line_ic = QtWidgets.QLineEdit(addclient)
        self.line_ic.setObjectName("line_ic")
        self.horizontalLayout_5.addWidget(self.line_ic)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.email = QtWidgets.QLabel(addclient)
        self.email.setMinimumSize(QtCore.QSize(43, 0))
        self.email.setObjectName("email")
        self.horizontalLayout_4.addWidget(self.email)
        self.line_email = QtWidgets.QLineEdit(addclient)
        self.line_email.setObjectName("line_email")
        self.horizontalLayout_4.addWidget(self.line_email)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.contact = QtWidgets.QLabel(addclient)
        self.contact.setMinimumSize(QtCore.QSize(43, 0))
        self.contact.setObjectName("contact")
        self.horizontalLayout_6.addWidget(self.contact)
        self.line_contact = QtWidgets.QLineEdit(addclient)
        self.line_contact.setObjectName("line_contact")
        self.horizontalLayout_6.addWidget(self.line_contact)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(addclient)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.line_remark = QtWidgets.QLineEdit(addclient)
        self.line_remark.setMinimumSize(QtCore.QSize(361, 91))
        self.line_remark.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.line_remark.setObjectName("line_remark")
        self.horizontalLayout.addWidget(self.line_remark)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(addclient)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)

        self.retranslateUi(addclient)
        self.buttonBox.accepted.connect(addclient.accept) # type: ignore
        self.buttonBox.rejected.connect(addclient.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addclient)

    def retranslateUi(self, addclient):
        _translate = QtCore.QCoreApplication.translate
        addclient.setWindowTitle(_translate("addclient", "Add client"))
        self.name.setText(_translate("addclient", "Name"))
        self.client_id.setText(_translate("addclient", "Referral code"))
        self.deposit.setText(_translate("addclient", "IC Number"))
        self.email.setText(_translate("addclient", "Email"))
        self.contact.setText(_translate("addclient", "Contact"))
        self.label_6.setText(_translate("addclient", "Remark"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addclient = QtWidgets.QDialog()
    ui = Ui_addclient()
    ui.setupUi(addclient)
    addclient.show()
    sys.exit(app.exec_())
