# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staff_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame, QWidget
from PyQt5.QtWidgets import QPushButton, QSizePolicy


class Ui_Staff(object):
    def setupUi(self, Staff):
        Staff.setObjectName("Staff")
        Staff.resize(638, 489)
        if Staff.layout() is not None:
        # Delete the existing layout
                QWidget().setLayout(Staff.layout())
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Staff)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(Staff)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    background-color: rgb(226, 226, 226);\n"
"}\n"
"\n"
"QPushButton:Hover{\n"
"    background-color: rgb(213, 213, 213);\n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    background-color: rgb(166, 166, 166);\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.title_label = QtWidgets.QLabel(self.widget_2)
        self.title_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.title_label.setFont(font)
        self.title_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_4.addWidget(self.title_label)
        spacerItem1 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.export_btn = QtWidgets.QPushButton(self.widget_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sys client management/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_btn.setIcon(icon)
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout.addWidget(self.export_btn)
        self.delete_btn = QtWidgets.QPushButton(self.widget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sys client management/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_btn.setIcon(icon1)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        spacerItem2 = QtWidgets.QSpacerItem(438, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_btn = QtWidgets.QPushButton(self.widget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sys client management/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon2)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_3.addWidget(self.add_btn)
        self.edit_btn = QtWidgets.QPushButton(self.widget_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/sys client management/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_btn.setIcon(icon3)
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout_3.addWidget(self.edit_btn)
        self.refresh_btn = QtWidgets.QPushButton(self.widget_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/sys client management/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn.setIcon(icon4)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_3.addWidget(self.refresh_btn)
        spacerItem3 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchbar = QtWidgets.QLineEdit(self.widget_2)
        self.searchbar.setMinimumSize(QtCore.QSize(160, 21))
        self.searchbar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchbar.setClearButtonEnabled(False)
        self.searchbar.setObjectName("searchbar")
        self.horizontalLayout_2.addWidget(self.searchbar)
        self.search_btn = QtWidgets.QPushButton(self.widget_2)
        self.search_btn.setMinimumSize(QtCore.QSize(22, 22))
        self.search_btn.setStyleSheet("border-radius: 10px;")
        self.search_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/sys client management/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon5)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_2.addWidget(self.search_btn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table_staff = QtWidgets.QTableWidget(self.widget_3)
        self.table_staff.setStyleSheet("QHeaderView::section{\n"
"    background-color: rgb(195, 195, 195);;\n"
"}\n"
"QTableWidget::Item{ \n"
"    color:black;    \n"
"}\n"
"")
        self.table_staff.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_staff.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table_staff.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_staff.setGridStyle(QtCore.Qt.SolidLine)
        self.table_staff.setObjectName("table_staff")
        self.table_staff.setColumnCount(7)
        self.table_staff.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_staff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_staff.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_staff.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_staff.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_staff.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_staff.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_staff.setHorizontalHeaderItem(6, item)
        self.table_staff.horizontalHeader().setSortIndicatorShown(True)
        self.table_staff.horizontalHeader().setStretchLastSection(True)
        self.table_staff.verticalHeader().setVisible(False)
        self.table_staff.verticalHeader().setCascadingSectionResizes(False)
        self.table_staff.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.table_staff)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_4.addWidget(self.widget)

        self.retranslateUi(Staff)
        QtCore.QMetaObject.connectSlotsByName(Staff)

    def retranslateUi(self, Staff):
        _translate = QtCore.QCoreApplication.translate
        Staff.setWindowTitle(_translate("Staff", "Staff Manager"))
        self.title_label.setText(_translate("Staff", "STAFF"))
        self.export_btn.setText(_translate("Staff", "Export"))
        self.delete_btn.setText(_translate("Staff", "Delete"))
        self.add_btn.setText(_translate("Staff", "Add"))
        self.edit_btn.setText(_translate("Staff", "Edit"))
        self.refresh_btn.setText(_translate("Staff", "Refresh"))
        self.searchbar.setPlaceholderText(_translate("Staff", "Search..."))
        self.table_staff.setSortingEnabled(True)
        item = self.table_staff.horizontalHeaderItem(0)
        item.setText(_translate("Staff", "Num"))
        item = self.table_staff.horizontalHeaderItem(1)
        item.setText(_translate("Staff", "Name"))
        item = self.table_staff.horizontalHeaderItem(2)
        item.setText(_translate("Staff", "Username"))
        item = self.table_staff.horizontalHeaderItem(3)
        item.setText(_translate("Staff", "Referral Code"))
        item = self.table_staff.horizontalHeaderItem(4)
        item.setText(_translate("Staff", "Email"))
        item = self.table_staff.horizontalHeaderItem(5)
        item.setText(_translate("Staff", "Password"))
        item = self.table_staff.horizontalHeaderItem(6)
        item.setText(_translate("Staff", "Logged in"))
import clientsysmanagenent_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Staff = QtWidgets.QWidget()
#     ui = Ui_Staff()
#     ui.setupUi(Staff)
#     Staff.show()
#     sys.exit(app.exec_())
